### ISSUE TITLE
"*." doesn't start a new bullets list

### ISSUE THREAD

**Issue by jmuheim** [Access4all/EPUB#53]
> Same with unordered list if you start a line with *.

This isn't true: a hyphen starts a new bullets list! This is the expected behaviour anyway (at least from my point of view), so just fix the text.

**Comment by qtnc** [comment]
As discussed, the confusion comes from the fact that the star is 
followed by a dot in the tutorial. To create a list, its star space some 
text and then the list is created when pressing enter.
