### ISSUE TITLE
YouTube videos don't have proper dimensions

### ISSUE THREAD

**Issue by jmuheim** [Access4all/EPUB#59]
When copy&pasting a YouTube link, the iframe doesn't have proper dimensions: `width="100%"` and `height="auto"` doesn't automatically expand the height, because the content of the iframe is not known by the iframe itself.

![](https://cloud.githubusercontent.com/assets/1814983/6370577/535b096c-bcf2-11e4-8f5a-43cffcd10b9b.png)

Some inspiration here: http://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

**Comment by qtnc** [comment]
I have copied the code coming from the website given. You may try again 
to see if it changed something.
It will only work in a fresh new book.

**Comment by jmuheim** [comment]
It's looking better now, it's not 100% width anymore. It's a bit small, but it doesn't look like a bug anymore, so I will close this.

Still, you should look into a solution for offering containers like left50, right33, etc., as you offer on adding images.
