### ISSUE TITLE
Many JS errors when interacting

### ISSUE THREAD

**Issue by jmuheim** [Access4all/EPUB#64]
I get a lot of JS errors on the console when interacting with the editor.

For example:

```
Uncaught TypeError: Cannot read property 'text' of undefinedselect_text.js:1 gselect_text.js:1 (anonymous function)jquery.js:63 c.event.handlejquery.js:56 c.event.add.h.handle.n
```

![](https://cloud.githubusercontent.com/assets/1814983/6371046/e0226cbe-bcf7-11e4-8227-2e0d2e1eb8b9.png)

I suggest you're using some sort of automatic JS error notification, so you always get notified when an error occurs. I have no idea though whether there are accessible solutions for this, e.g. a Firefox plugin.

**Comment by jmuheim** [comment]
For Chrome, there is [JavaScript Errors Notifier](https://chrome.google.com/webstore/detail/javascript-errors-notifie/jafmfknfnkoekkdocjiaipcnmkklaajd).

**Comment by qtnc** [comment]
The error you have posted contains the word jquery; it is obviously not 
coming from my code, as I'm not using JQuery. I don't know by which 
black magic it is still loaded !
This particular one probably comes for whatever extension you have in 
your browser.

I have sort of debug indications, if I activate debug mode
global.js: set debug=true.
For more advanced things, it would be indeed extremely useful to have an 
accessible console/debugger/reporter. I already tried firebug but the 
parts I'm the most interested in aren't accessible; I don't know if 
there are accessible alternatives. Builtin consoles/debuggers of newest 
IE, Chrome and firefox are far from fully accessible.

**Comment by qtnc** [comment]
Ah nice, I will try this extension out and see if it is accessible.

**Comment by jmuheim** [comment]
You're right about jquery. I will get a new Mac this week, so I won't dig into this one any deeper, and hope it won't occur again.
